My Protflolio/My_Portifolio/My_Portifolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('about.urls')),
    path('',include('resume.urls')),
    path('',include('projects.urls')),
    ]#+static(settings.STATIC_URL, document_root=settings.STAIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My Protflolio/My_Portifolio/about/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views



urlpatterns = [
    path('',views.home, name='About Me'),
    path('contact_me/',views.contact_me, name='Contact Me' )
]

My Protflolio/My_Portifolio/projects/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views



urlpatterns = [
    path('projects/', views.project, name='Projects'),
]

My Protflolio/My_Portifolio/resume/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('resume/',views.resume, name="Resume"),
    

]

My Protflolio/My_Portifolio/about/models.py
import email
from email.policy import default
from operator import getitem
from django.db import models



class Profile(models.Model):
    
    avatar = models.ImageField(default='img/default.jpeg', upload_to='img/')
    f_name= models.CharField(max_length=50)
    l_name = models.CharField(max_length=50)

    about= models.TextField(default='About Me')
    git_link = models.URLField(default='https://github.com/Gaurav065')
    
    link_link = models.URLField(default='https://www.linkedin.com/in/gaurav-patel-a822931bb/')

    phone_number = models.CharField(default='+91-9721645391', max_length=15)
    email = models.EmailField(default='gaurav.patel.gpp@gmail.com')

    
    def full_name(self):
        return self.f_name +" "+ self.l_name

My Protflolio/My_Portifolio/projects/models.py
from os import link
from django.db import models
from django.forms import ModelForm
from resume.models import skill,experience

class Project(models.Model):
    project_name = models.CharField(max_length=100)
    sk = models.ManyToManyField('resume.skill', related_name='sk')
    link = models.URLField(default='https://github.com/Gaurav065')
    description = models.TextField(default=project_name, max_length=300)
    client= models.ForeignKey('resume.experience', on_delete=models.CASCADE)

    def __str__(self):
        return self.project_name

class achievement(models.Model):
    achievements = models.CharField(default='Current work', max_length=300)



My Protflolio/My_Portifolio/resume/models.py
from django.db import models
import datetime
from django import forms
from django.forms import ModelForm


jobs =(
    ("1", "Frontend dev"),
    ("2", "Backend dev"),
    ("3", "Full Stack"),
    ("4", "Software developer"),
    ("5", "Data Scientist"),
    ("6", "Data Engineer"),
    ("7", "Database Administrator"),
    ("8", "Machine Learning Engineer"),
    ("9", "Software Architect"),
    ("10", "Dev Ops Engineer"),
    ("11", "Cloud Engineer"),
    ("12", "IT project Manager"),
    ("13", "Enterprise Architect"),
)


type_j = (
    ("1", "Internship"),
    ("2", "Full time"),
    ("3", "Part Time"),
    ("4", "Freelancing"),
)


# pr_ln = (
#     ("1", "Python"),
#     ("2", "Java"),
#     ("3", "C"),
#     ("4", "C++"),
#     ("5", "C#"),
#     ("6", "Rust"),
#     ("7", "GoLang"),
#     ("8", "SQL"),
#     ("9", "PHP"),
#     ("10", "Scala"),
#     ("11", "Swift"),
#     ("12", "Matlab"),
#     ("13", "Kotlin"),
#     ("14", "Node.js"),
#     ("15", "React.js"),
#     ("16", "CSS"),
#     ("17", "HTML"),
#     ("18", "TypeScript"),
#     ("19", "Ruby"),
# )

# type_j = (
#     ("1", "Internship"),
#     ("2", "Full time"),
#     ("3", "Part Time"),
#     ("4", "Freelancing"),
# )


# db = (
#     ("1", "MongoDB"),
#     ("2", "Postgres"),
#     ("3", "MySQL"),
# )


class education(models.Model):
    
    university = models.CharField(default="Lovely Professional University", max_length=100)
    course = models.CharField(default='B.Tech CSE with specialization In ML and AI', max_length=100)
    gpa = models.FloatField(default=7.54, max_length=10.0)

    date_start = models.DateField(("Date"), default=datetime.date.today)
    date_end = models.DateField(("Date"), default=datetime.date.today)

    location = models.CharField(default='Phagwara, Punjab, India, 144411', max_length=150)

    

class experience(models.Model):

    job= models.CharField(default='None', max_length=200,choices=jobs)
    company_name = models.CharField(default='Client_Based', max_length=100)

    job_type = models.CharField(default='None',max_length=200, choices=type_j)

    description = models.TextField(default=job, max_length=300)
    location = models.CharField(default='India', max_length=50)
    end_date = models.DateField(('Date'), default=datetime.date.today)
    start_date = models.DateField(("Date"), default=datetime.date.today)

    def __str__(self):
        return self.job_type


class skill(models.Model):
    skill_type = (
        ("P","Programming Language"),
        ("M","Modules/Libraries"),
        ("T","Tools"),
        ("D","Databases"),
    )
    
    typeof = models.CharField(default="P",max_length=20,choices=skill_type)
    name = models.CharField(default="Python", max_length=25)
    def __str__(self):
        return self.name

    # modules_libraries = models.CharField(default='python libraries', max_length=400)
    # tools = models.CharField(default='VS code, Github, pyqt designer, unreal engine, adobe, etc', max_length=200)
    # databases = models.CharField(default='SQL',choices=db,max_length=100)
    # programming_languages=models.CharField(default='Python',choices=pr_ln,max_length=100)



class certificates(models.Model):
    name = models.CharField(default="best programmer", max_length=100)
    url = models.URLField()
    certi = models.ImageField(default='img/Screenshot 2022-08-21 054646.png', upload_to='img/')

    def __str__(self):
        return self.name

My Protflolio/My_Portifolio/about/views.py
from django.shortcuts import render
from django.urls import path, include
from .models import Profile


def home(request):
    X=Profile.objects.get(id=1)
    context={'me':X}
    return render(request, 'home.html',context)

def contact_me(request):
    X=Profile.objects.get(id=1)
    context={'me':X}
    return render(request,'contact.html',context)

My Protflolio/My_Portifolio/projects/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def project(request):
    projects=Project.objects.all()
    print(len(projects))
    context={'project':projects}
    return render(request,'projects.html', context)

My Protflolio/My_Portifolio/resume/views.py
from multiprocessing import context
from django.shortcuts import render
from django.urls import path, include
from .models import education, experience, certificates, skill
import mimetypes
from django.shortcuts import HttpResponse

def resume(request):

    education_details = education.objects.get(id=1)

    experience_detail = experience.objects.all()

    skill_details = skill.objects.all()

    ctf = certificates.objects.all()

    context = {
        'experience_detail': experience_detail,
        'education_details': education_details,
        'sk_d': skill_details,
        'ct': ctf,
    }

    return render(request, 'resume.html', context)


# def download_file(request):
#     fl_path = 'C:\Users\dell\Desktop\learn_django\My Protflolio\My_Portifolio\media\img\Screenshot 2022-08-21 054646.png'
#     filename = 'resume.pdf'

#     fl = open(fl_path, 'r')
#     mime_type, _ = mimetypes.guess_type(fl_path)
#     response = HttpResponse(fl, content_type=mime_type)
#     response['Content-Disposition'] = "attachment; filename=%s" % filename
#     return response

My Protflolio/My_Portifolio/templates/contact.html
{% extends 'main.html' %}

{% block title %}Contact Me{% endblock title %}

{% block content %}

<h1>this is the contatct me</h1>

<div class="profile">
    <img src="/media/{{me.avatar}}" height="100px" width="100px" alt="">
</div>

<div class="main">
    {{me.full_name}}
    <br>
    {{me.about}}
    <br>
    {{me.git_link}}
    <br>
    {{me.link_link}}
    <br>
    {{me.phone_number}}
    <br>
    {{me.email}}
</div>
{% endblock content %}

My Protflolio/My_Portifolio/templates/home.html
{%extends 'main.html'%}

{%block title%} Home{%endblock title%}

{%block content%}


<div class="profile">

    <img src="/media/{{me.avatar}}" height="100px" width="100px" alt="">
</div>


<div class="main">
    <div class="heading">
        {{me.full_name.title}}
    </div>
    
    <br>{{me.about}}
    
    <br>
</div>

<!-- <div class="frame">
</div> -->

<a href="/resume"><button class="rbtn" type="button"><span>Resume</span></button></a>

    <!-- <button type="button">Resume</button> -->




{%endblock%}

My Protflolio/My_Portifolio/templates/main.html


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/media/css/style.css">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
{%block content%}
<h1>this is home page</h1>
{%endblock%}
</body>
</html>

My Protflolio/My_Portifolio/templates/projects.html
{% extends 'main.html' %} 

{% block title %}Projects{% endblock title %} 


{% block content %}
<h1> projects</h1>

{% for prj in project%}

    

<h1>{{prj.project_name}}</h1>
<h2>Description <p>
    {{prj.description}}
</p></h2>
<h2>Link <p>
    {{prj.link}}
</p></h2>
<h2>Client<p>
    {{prj.get_client_display}}
</p></h2>
<p>
{% for skill in  prj.sk.all %}
{{skill.name}}({{skill.get_typeof_display}}), 


{% endfor %}
</p>

{%endfor%}


<a href="/contact_me">
    <button type="button">Contact Me</button>
</a>

{% endblock content %}

My Protflolio/My_Portifolio/templates/resume.html
{% extends 'main.html' %}

{% block title %}Resume{% endblock title %}

{% block content %}

<h1>Resume</h1>
<div class="rs">
<div class="Education">
    <h1>Education</h1>
    <div class="education_details">
    <h3>{{education_details.university}}</h3>
    <h3>{{education_details.course}}</h>
    <h3>{{education_details.gpa}}</h3>
    <h3>{{education_details.location}}</h3>
    <h3>{{education_details.date_start}}-{{education_details.date_end}}</h3>
    </div>
</div>

<div class="experiance">
    {% for exp in experience_detail %}
    <h1>{{exp.get_job_display}}</h1>
    <h2>{{exp.get_company_name_display}}</h2>
    <h3>{{exp.get_job_type_display}}</h3>
    <h4>{{exp.description}}</h4>
    <h4>{{exp.location}}}</h4>
    <h4>{{exp.end_date}}-{{exp.start_date}}</h4>    
    {% endfor %}
</div>


<div class="certificates">
    {% for c in ct %}
    <h2>{{c.url}}</h2>
    <h3>{{c.name}}</h3>
    {% endfor %}
</div>


<div class="Skills">
    {% for s in sk_d %}
    <h1>{{s.get_typeof_display}}</h1>
    <h2>{{s.name}}</h2>
    {% endfor %}
</div>


</div>
    
    <div class="button_project_page">
        <a href="/projects">
            <button type="button">Projects</button>
        </a>
    </div>
    
    
    {% endblock content %}